# create directory for generated files

if (!file.exists("generated")) dir.create("generated")

styles <- readLines("styles.txt")
# (mokokai doesn't work)

# create files
create_qmd <- function(style_name) {
  contents <- readLines("template.qmd")
  gsub("placeholder", style_name, contents) |> 
    writeLines(con = paste0("generated/", style_name, ".qmd"))
}

# create .qmd files
lapply(styles, create_qmd)

# render .qmd files
quarto::quarto_render("generated/*.qmd")

# crop and save as png
files <- list.files("generated", "*.html")

# note: if you change the code in template.qmd, you may need to
# adjust vwidth 
webshot::webshot(paste0("generated/", files), 
                 file = paste0("generated/", "webshot.png"),
                 selector = ".cell", zoom = 4, vwidth = 415)

# create README
add_image <- function(image) paste0("![](generated/", image, ")")

writeLines(c("# Quarto syntax highlighting examples", "",
             "<!-- Generated by create_syntax_examples.R, do not edit. -->", "",
             "see: https://quarto.org/docs/output-formats/html-code.html#highlighting", "",
             "to create your own examples, edit `template.qmd` then run the",
             "code in `create_syntax_examples.R`", "",
             unlist(lapply(list.files("generated", "*.png"), add_image))),
           "README.md")
